/* File automatically generated by the macro OPENCOG_ADD_ATOM_TYPES. Do not edit */
#include <opencog/atoms/base/types.h>
namespace opencog
{
extern opencog::Type HEBBIAN_LINK;
extern opencog::Type ASYMMETRIC_HEBBIAN_LINK;
extern opencog::Type SYMMETRIC_HEBBIAN_LINK;
extern opencog::Type INVERSE_HEBBIAN_LINK;
extern opencog::Type SYMMETRIC_INVERSE_HEBBIAN_LINK;
} // namespace opencog
