
; DO NOT EDIT THIS FILE! This file was automatically
; generated from atom definitions in types.script by the macro OPENCOG_ADD_ATOM_TYPES
;
; This file contains basic scheme wrappers for atom creation.
;
(define-module (opencog))
(define-public HebbianLinkType (cog-type->int 'HebbianLink))
(define-public (HebbianLink . x)
	(apply cog-new-link (append (list HebbianLinkType) x)))
(define-public (Hebbian . x)
	(apply cog-new-link (append (list HebbianLinkType) x)))
(define-public AsymmetricHebbianLinkType (cog-type->int 'AsymmetricHebbianLink))
(define-public (AsymmetricHebbianLink . x)
	(apply cog-new-link (append (list AsymmetricHebbianLinkType) x)))
(define-public (AsymmetricHebbian . x)
	(apply cog-new-link (append (list AsymmetricHebbianLinkType) x)))
(define-public SymmetricHebbianLinkType (cog-type->int 'SymmetricHebbianLink))
(define-public (SymmetricHebbianLink . x)
	(apply cog-new-link (append (list SymmetricHebbianLinkType) x)))
(define-public (SymmetricHebbian . x)
	(apply cog-new-link (append (list SymmetricHebbianLinkType) x)))
(define-public InverseHebbianLinkType (cog-type->int 'InverseHebbianLink))
(define-public (InverseHebbianLink . x)
	(apply cog-new-link (append (list InverseHebbianLinkType) x)))
(define-public (InverseHebbian . x)
	(apply cog-new-link (append (list InverseHebbianLinkType) x)))
(define-public SymmetricInverseHebbianLinkType (cog-type->int 'SymmetricInverseHebbianLink))
(define-public (SymmetricInverseHebbianLink . x)
	(apply cog-new-link (append (list SymmetricInverseHebbianLinkType) x)))
(define-public (SymmetricInverseHebbian . x)
	(apply cog-new-link (append (list SymmetricInverseHebbianLinkType) x)))
